# Generated by Django 5.2 on 2025-04-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0015_order_is_paid_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_no',
            field=models.CharField(max_length=30),
        ),
    ]
